---
abstract: 'keeps safe database connection'
author:
  - 'Yury Zavarin <yury.zavarin@gmail.com>'
build_requires:
  Test::Class: '0'
  Test::Exception: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.032, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBD-Safe
requires:
  DBD::File: '0'
  DBI: '0'
  Time::HiRes: '0'
  base: '0'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  homepage: http://github.com/tadam/DBD-Safe
  repository: git://github.com/tadam/DBD-Safe
version: '0.07'
